---
typo3:
  prefix:
    config: /usr/local/etc
    var: /var/www/typo3
    # Deployer-style release path
    current_release: /var/www/typo3/current
    # Surf-style release path
    # current_release: /var/www/typo3/releases/current
  oauth2_proxy:
